[package]
name = "sway-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
nanoid = "0.4.0"
fs_extra = "1.2.0"
hex = "0.4.3"
hyper = { version = "0.14.23", features = ["http1", "server", "tcp"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0.91"
regex = "1.7.0"