name: GitHub Pages

on:
  push:

env:
  NODE_VERSION: '16'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: npm ci and build
        env:
          CI: true
        run: |
          cd app && npm ci && npm run build
          cp -r build ../build
