name: GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  NODE_VERSION: '16'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./frontend